import { useCallback, useEffect, useMemo, useState } from "react";
import { useOutletContext, useSearchParams } from "react-router-dom";
import { Loader2, MessageSquarePlus, Send } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { api } from "@/lib/api";
import { formatDate, queryForClient } from "./controlData";
import { EmptyState, PageIntro, PageLoader, Panel, StatusPill } from "./ControlUi";

const STATUS = { aperto:"Aperto", in_lavorazione:"In lavorazione", attesa_cliente:"Attesa cliente", attesa_corriere:"Attesa corriere", risolto:"Risolto", chiuso:"Chiuso" };
const CATEGORY = { ordine:"Ordine", spedizione:"Spedizione", stock:"Stock", reso:"Reso", fatturazione:"Fatturazione", altro:"Altro" };
const ACTION_SUBJECT = { pausa:"Richiesta pausa ordine", indirizzo:"Richiesta modifica indirizzo", prodotti:"Richiesta modifica prodotti", assistenza:"Richiesta assistenza ordine" };

export default function ControlTickets() {
  const context=useOutletContext(); const [params,setParams]=useSearchParams();
  const [tickets,setTickets]=useState(null); const [orders,setOrders]=useState([]); const [selected,setSelected]=useState(null); const [messages,setMessages]=useState([]); const [reply,setReply]=useState(""); const [sending,setSending]=useState(false);
  const [form,setForm]=useState({ subject:ACTION_SUBJECT[params.get("action")] || "", category:params.get("category") || "ordine", order_id:params.get("order_id") || "", message:"" });
  const [creating,setCreating]=useState(false); const showCreate=params.get("new") === "1" || Boolean(params.get("order_id"));
  const load=useCallback(async()=>{ const suffix=queryForClient(context.clientId); const [t,o]=await Promise.all([api.get(`/wms/tickets${suffix}`).catch(()=>({data:[]})),api.get(`/shopify/orders${suffix}`)]); setTickets(t.data||[]); setOrders(o.data||[]); },[context.clientId]);
  useEffect(()=>{ setTickets(null); load(); },[load]);
  const selectedId=selected?.id;
  useEffect(()=>{ if(!selectedId){setMessages([]);return;} api.get(`/wms/tickets/${selectedId}/messages`).then((r)=>setMessages(r.data||[])); },[selectedId]);
  const selectedOrder=useMemo(()=>orders.find((o)=>o.id===form.order_id),[orders,form.order_id]);
  if(!tickets) return <PageLoader/>;
  const create=async()=>{ if(!form.subject.trim() || !form.message.trim()){toast.error("Inserisci oggetto e messaggio");return;} const clienteId=context.clientId || selectedOrder?.cliente_id; if(context.isStaff && !clienteId){toast.error("Seleziona un cliente o un ordine");return;} setCreating(true); try{await api.post("/wms/tickets",{...form,cliente_id:clienteId,order_id:form.order_id||null});toast.success("Ticket aperto");setForm({subject:"",category:"ordine",order_id:"",message:""});setParams({});await load();}catch(e){toast.error(e.response?.data?.detail||e.message);}finally{setCreating(false);}};
  const send=async()=>{if(!reply.trim())return;setSending(true);try{await api.post(`/wms/tickets/${selected.id}/messages`,{body:reply});setReply("");const r=await api.get(`/wms/tickets/${selected.id}/messages`);setMessages(r.data||[]);await load();}catch(e){toast.error(e.response?.data?.detail||e.message);}finally{setSending(false);}};
  const updateStatus=async(status)=>{try{await api.put(`/wms/tickets/${selected.id}`,{status});setSelected({...selected,status});await load();toast.success("Stato aggiornato");}catch(e){toast.error(e.response?.data?.detail||e.message);}};
  return <div><PageIntro eyebrow="Assistenza contestuale" title="Ticket" description="Ogni richiesta resta collegata all'ordine e conserva tutta la conversazione tra cliente e logistica." action={<Button onClick={()=>setParams({new:"1"})}><MessageSquarePlus className="mr-2 h-4 w-4"/>Nuovo ticket</Button>}/>
   {showCreate && <Panel className="mb-4" title="Apri una richiesta" description="Descrivi in modo operativo cosa deve fare Aimago"><div className="grid gap-4 p-5 lg:grid-cols-2"><div><label className="text-xs font-bold">Ordine collegato</label><Select value={form.order_id || "none"} onValueChange={(v)=>setForm({...form,order_id:v==="none"?"":v})}><SelectTrigger className="mt-1"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Nessun ordine</SelectItem>{orders.map((o)=><SelectItem key={o.id} value={o.id}>{o.order_name} {context.isStaff ? `· ${o.cliente_ragione_sociale || ""}`:""}</SelectItem>)}</SelectContent></Select></div><div><label className="text-xs font-bold">Categoria</label><Select value={form.category} onValueChange={(v)=>setForm({...form,category:v})}><SelectTrigger className="mt-1"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(CATEGORY).map(([k,v])=><SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select></div><div className="lg:col-span-2"><label className="text-xs font-bold">Oggetto</label><Input className="mt-1" value={form.subject} onChange={(e)=>setForm({...form,subject:e.target.value})} placeholder="Es. Bloccare ordine prima della preparazione"/></div><div className="lg:col-span-2"><label className="text-xs font-bold">Messaggio</label><textarea className="mt-1 min-h-28 w-full rounded-md border border-slate-200 p-3 text-sm outline-none focus:border-teal-600" value={form.message} onChange={(e)=>setForm({...form,message:e.target.value})} placeholder="Indica la modifica o il problema da risolvere"/></div><div className="flex gap-2 lg:col-span-2"><Button onClick={create} disabled={creating}>{creating && <Loader2 className="mr-2 h-4 w-4 animate-spin"/>}Invia richiesta</Button><Button variant="outline" onClick={()=>setParams({})}>Annulla</Button></div></div></Panel>}
   <div className="grid gap-4 xl:grid-cols-[0.85fr_1.15fr]"><Panel title="Conversazioni" description={`${tickets.length} ticket`}>{tickets.length ? <div className="max-h-[620px] divide-y divide-slate-100 overflow-y-auto">{tickets.map((t)=><button key={t.id} onClick={()=>setSelected(t)} className={`w-full p-5 text-left hover:bg-slate-50 ${selected?.id===t.id?"bg-teal-50":""}`}><div className="flex items-start justify-between gap-3"><p className="font-extrabold">{t.subject}</p><StatusPill tone={["risolto","chiuso"].includes(t.status)?"emerald":t.priority==="urgente"?"rose":"amber"}>{STATUS[t.status]||t.status}</StatusPill></div><p className="mt-2 text-xs text-slate-500">{t.order?.order_name || CATEGORY[t.category]} · {formatDate(t.updated_at,true)}</p>{context.isStaff&&<p className="mt-1 text-xs font-bold text-teal-700">{t.cliente?.ragione_sociale}</p>}</button>)}</div>:<EmptyState title="Nessun ticket" description="Le richieste su ordini, stock e spedizioni compariranno qui."/>}</Panel>
   <Panel title={selected?.subject || "Dettaglio ticket"} description={selected ? `${selected.order?.order_name || CATEGORY[selected.category]} · aperto ${formatDate(selected.created_at)}`:"Seleziona una conversazione"} action={selected&&context.isStaff?<Select value={selected.status} onValueChange={updateStatus}><SelectTrigger className="h-9 w-44"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(STATUS).map(([k,v])=><SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select>:null}>
    {selected ? <div className="flex min-h-[520px] flex-col"><div className="flex-1 space-y-3 overflow-y-auto p-5">{messages.map((m)=><div key={m.id} className={`max-w-[86%] rounded-md p-3 ${m.author?.role === "cliente" ? "bg-slate-100" : "ml-auto bg-teal-700 text-white"}`}><p className="text-sm leading-6">{m.body}</p><p className={`mt-2 text-[10px] font-bold ${m.author?.role === "cliente"?"text-slate-500":"text-teal-100"}`}>{m.author?.name || (m.author?.role === "cliente"?"Cliente":"Aimago")} · {formatDate(m.created_at,true)}</p></div>)}</div><div className="flex gap-2 border-t border-slate-100 p-4"><Input value={reply} onChange={(e)=>setReply(e.target.value)} onKeyDown={(e)=>{if(e.key==="Enter")send();}} placeholder="Scrivi una risposta"/><Button onClick={send} disabled={sending} aria-label="Invia"><Send className="h-4 w-4"/></Button></div></div>:<EmptyState title="Seleziona un ticket" description="Qui vedrai messaggi, ordine collegato e stato della richiesta."/>}
   </Panel></div>
  </div>;
}
