import { useCallback, useEffect, useMemo, useState } from "react";
import Papa from "papaparse";
import { useNavigate, useOutletContext } from "react-router-dom";
import { Ban, Download, FileCheck2, FileSpreadsheet, Loader2, MessageSquarePlus, PackageOpen, Pencil, Plus, Save, Search, ShoppingCart, Trash2, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { api } from "@/lib/api";
import { exceptionGuidance, formatDate, ORDER_STATUS, orderPieces, queryForClient } from "./controlData";
import { EmptyState, Metric, PageIntro, PageLoader, Panel, StatusPill } from "./ControlUi";

const FILTERS = [["all","Tutti"], ...Object.entries(ORDER_STATUS).map(([key,value]) => [key,value.label])];
const EMPTY_ORDER_FORM = {ship_name:"",ship_company:"",ship_address1:"",ship_address2:"",ship_zip:"",ship_city:"",ship_province:"",ship_country:"Italia",ship_country_code:"IT",customer_phone:"",customer_email:"",note:"",items:[]};

export default function ControlOrders() {
  const context = useOutletContext(); const navigate = useNavigate();
  const [orders,setOrders] = useState(null); const [filter,setFilter] = useState("all"); const [search,setSearch] = useState("");
  const [csvOpen,setCsvOpen] = useState(false);
  const [editingOrder,setEditingOrder] = useState(null);
  const [cancellingOrder,setCancellingOrder] = useState(null);
  const loadOrders = useCallback(() => { setOrders(null); return api.get(`/shopify/orders${queryForClient(context.clientId)}`).then((r) => setOrders(r.data || [])); }, [context.clientId]);
  useEffect(() => { loadOrders(); }, [loadOrders]);
  const visible = useMemo(() => (orders || []).filter((o) => (filter === "all" || o.wms_status === filter) && [o.order_name,o.customer_email,o.ship_name,o.cliente_ragione_sociale].join(" ").toLowerCase().includes(search.toLowerCase())), [orders,filter,search]);
  if (!orders) return <PageLoader />;
  const requestAction = (order, action) => navigate(`/wms/tickets?order_id=${order.id}&category=ordine&action=${action}`);
  const active = orders.filter((o) => !["spedito","annullato"].includes(o.wms_status));
  return <div><PageIntro eyebrow="Flusso outbound" title="Ordini" description="Segui ogni ordine dal suo ingresso fino alla spedizione. Le richieste di modifica vengono registrate come ticket tracciabili." action={<Button onClick={()=>setCsvOpen(true)} disabled={context.isStaff && !context.clientId}><Upload className="mr-2 h-4 w-4"/>Importa ordini CSV</Button>} />
    <div className="grid gap-3 sm:grid-cols-3"><Metric label="Ordini visibili" value={orders.length} icon={ShoppingCart}/><Metric label="Aperti" value={active.length} hint={`${active.reduce((s,o) => s + orderPieces(o),0)} pezzi`} icon={PackageOpen} tone="amber"/><Metric label="Spediti" value={orders.filter((o) => o.wms_status === "spedito").length} icon={PackageOpen} tone="emerald"/></div>
    <Panel className="mt-4" title="Elenco ordini" description={`${visible.length} risultati`} action={<div className="relative w-60"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Cerca ordine" className="h-9 pl-9"/></div>}>
      <div className="flex gap-2 overflow-x-auto border-b border-slate-100 px-5 py-3">{FILTERS.map(([key,label]) => <button key={key} onClick={() => setFilter(key)} className={`shrink-0 rounded-md px-3 py-2 text-xs font-extrabold ${filter === key ? "bg-slate-950 text-white" : "bg-slate-100 text-slate-600"}`}>{label}</button>)}</div>
      {visible.length ? <div className="divide-y divide-slate-100">{visible.map((order) => { const status=ORDER_STATUS[order.wms_status] || {label:order.wms_status,tone:"slate"}; const editable=["in_verifica","eccezione","da_preparare"].includes(order.wms_status); const cancellable=order.wms_status === "da_preparare"; const guidance=order.wms_status === "eccezione" || order.exception_type ? exceptionGuidance(order) : null; return <div key={order.id} className="grid gap-4 px-5 py-5 xl:grid-cols-[1.1fr_0.7fr_0.55fr_auto] xl:items-center"><div><div className="flex flex-wrap items-center gap-2"><p className="font-extrabold">{order.order_name || "Ordine"}</p><StatusPill tone={status.tone}>{status.label}</StatusPill></div><p className="mt-1 text-xs text-slate-500">{order.ship_name || order.customer_email || "Destinatario non indicato"}</p>{guidance && <div className="mt-3 border-l-2 border-rose-400 pl-3"><p className="text-xs font-extrabold text-rose-700">{guidance.reason}</p><p className="mt-1 text-xs leading-5 text-slate-600">{guidance.action}</p></div>}{context.isStaff && <p className="mt-1 text-xs font-bold text-teal-700">{order.cliente_ragione_sociale}</p>}</div><div><p className="text-[10px] font-extrabold uppercase text-slate-400">Contenuto</p><p className="mt-1 text-sm font-bold">{(order.items || []).length} SKU · {orderPieces(order)} pezzi</p></div><div><p className="text-[10px] font-extrabold uppercase text-slate-400">Ricevuto</p><p className="mt-1 text-sm font-bold">{formatDate(order.processed_at || order.created_at)}</p></div><div className="flex flex-wrap justify-end gap-2"><Button variant="outline" size="sm" onClick={()=>setEditingOrder(order)} disabled={!editable} title={editable?"Modifica ordine":"Picking già iniziato"}><Pencil className="mr-2 h-4 w-4"/>Modifica</Button>{cancellable && <Button variant="outline" size="sm" className="border-rose-200 text-rose-700 hover:bg-rose-50 hover:text-rose-800" onClick={()=>setCancellingOrder(order)}><Ban className="mr-2 h-4 w-4"/>Annulla</Button>}<Button size="sm" onClick={()=>requestAction(order,"assistenza")}><MessageSquarePlus className="mr-2 h-4 w-4"/>Apri ticket</Button></div></div>; })}</div> : <EmptyState title="Nessun ordine" description="Non ci sono ordini compatibili con il filtro selezionato."/>}
    </Panel><CsvImportDialog open={csvOpen} onOpenChange={setCsvOpen} clientId={context.clientId} onImported={loadOrders}/><EditOrderDialog order={editingOrder} onOpenChange={(open)=>!open&&setEditingOrder(null)} onSaved={loadOrders}/><CancelOrderDialog order={cancellingOrder} onOpenChange={(open)=>!open&&setCancellingOrder(null)} onCancelled={loadOrders}/>
  </div>;
}

function CancelOrderDialog({ order, onOpenChange, onCancelled }) {
  const [busy,setBusy]=useState(false);
  const cancel=async()=>{setBusy(true);try{await api.put(`/shopify/orders/${order.id}`,{action:"cancel"});toast.success(`Ordine ${order.order_name} annullato`);onOpenChange(false);await onCancelled();}catch(error){toast.error(error.response?.data?.detail||error.message||"Ordine non annullato");}finally{setBusy(false);}};
  return <Dialog open={Boolean(order)} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-md"><DialogHeader><DialogTitle>Annullare {order?.order_name}?</DialogTitle><DialogDescription>L’ordine passerà da Nuovo ad Annullato e non potrà più entrare nel picking.</DialogDescription></DialogHeader><DialogFooter className="gap-2"><Button type="button" variant="outline" onClick={()=>onOpenChange(false)} disabled={busy}>Mantieni ordine</Button><Button type="button" className="bg-rose-700 text-white hover:bg-rose-800" onClick={cancel} disabled={busy}>{busy?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<Ban className="mr-2 h-4 w-4"/>}Conferma annullamento</Button></DialogFooter></DialogContent></Dialog>;
}

function CsvImportDialog({ open, onOpenChange, clientId, onImported }) {
  const [rows,setRows] = useState([]); const [fileName,setFileName] = useState(""); const [preview,setPreview] = useState(null); const [busy,setBusy] = useState(false);
  const reset = () => { setRows([]); setFileName(""); setPreview(null); };
  const handleOpen = (next) => { onOpenChange(next); if (!next) reset(); };
  const readFile = (file) => { reset(); if (!file) return; setFileName(file.name); Papa.parse(file,{header:true,skipEmptyLines:"greedy",transformHeader:(header)=>header.trim(),complete:({data,errors})=>{if(errors.length) return toast.error(`CSV non leggibile: ${errors[0].message}`);setRows(data || []);},error:(error)=>toast.error(error.message || "Impossibile leggere il CSV")}); };
  const check = async () => { if(!rows.length) return toast.error("Seleziona un file CSV"); setBusy(true); try { const {data}=await api.post("/wms/ordini/import-csv",{cliente_id:clientId,rows,dry_run:true}); setPreview(data); if(data.valid) toast.success("CSV valido e pronto"); } catch(error) { toast.error(error.response?.data?.detail || error.message); } finally { setBusy(false); } };
  const importRows = async () => { if(!preview?.valid) return; setBusy(true); try { const {data}=await api.post("/wms/ordini/import-csv",{cliente_id:clientId,rows,dry_run:false}); toast.success(`${data.imported} ordini importati`); handleOpen(false); await onImported(); } catch(error) { toast.error(error.response?.data?.detail || error.message); } finally { setBusy(false); } };
  const downloadTemplate = () => { const sample={numero_ordine:"ORD-1001",ean:"8050000000000",sku:"SKU-001",quantita:2,titolo:"Prodotto esempio",data_ordine:"2026-08-30",destinatario:"Mario Rossi",azienda:"",indirizzo:"Via Roma 1",cap:"00100",citta:"Roma",provincia:"RM",codice_paese:"IT",telefono:"",email:"",note:""}; const href=URL.createObjectURL(new Blob([Papa.unparse([sample])],{type:"text/csv;charset=utf-8"})); const link=document.createElement("a"); link.href=href; link.download="modello-ordini-aimago.csv"; link.click(); URL.revokeObjectURL(href); };
  return <Dialog open={open} onOpenChange={handleOpen}><DialogContent className="max-h-[88vh] overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle>Importa ordini da CSV</DialogTitle><DialogDescription>Una riga per prodotto. Le righe con lo stesso numero ordine verranno raggruppate automaticamente.</DialogDescription></DialogHeader>
    <div className="space-y-4"><div className="flex flex-wrap items-center gap-2"><label className="inline-flex h-10 cursor-pointer items-center rounded-md bg-slate-950 px-4 text-sm font-bold text-white"><Upload className="mr-2 h-4 w-4"/>Scegli CSV<input type="file" accept=".csv,text/csv" className="hidden" onChange={(event)=>readFile(event.target.files?.[0])}/></label><Button type="button" variant="outline" onClick={downloadTemplate}><Download className="mr-2 h-4 w-4"/>Scarica modello</Button>{fileName && <span className="text-sm font-semibold text-slate-600">{fileName} · {rows.length} righe</span>}</div>
      <div className="rounded-md border border-slate-200 bg-slate-50 p-3 text-xs leading-5 text-slate-600"><b>Colonne minime:</b> numero_ordine, quantita e almeno una tra ean, sku o fnsku. Per la spedizione aggiungi destinatario, indirizzo, cap, citta, provincia e codice_paese.</div>
      {preview && <div className="space-y-3"><div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><CsvMetric label="Ordini" value={preview.totals?.orders}/><CsvMetric label="Righe" value={preview.totals?.rows}/><CsvMetric label="Pezzi" value={preview.totals?.pieces}/><CsvMetric label="Non collegati" value={preview.totals?.unmatched} warn={preview.totals?.unmatched}/></div>{preview.errors?.length>0 && <div className="rounded-md bg-red-50 p-3 text-sm text-red-700">{preview.errors.slice(0,8).map((error)=><div key={error}>{error}</div>)}</div>}{preview.valid && <div className="flex items-center gap-2 rounded-md bg-emerald-50 p-3 text-sm font-bold text-emerald-800"><FileCheck2 className="h-5 w-5"/>File controllato: pronto per l’importazione.</div>}</div>}
    </div><DialogFooter className="gap-2"><Button type="button" variant="outline" onClick={check} disabled={busy || !rows.length}>{busy?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<FileSpreadsheet className="mr-2 h-4 w-4"/>}Controlla file</Button><Button type="button" onClick={importRows} disabled={busy || !preview?.valid}>{busy&&<Loader2 className="mr-2 h-4 w-4 animate-spin"/>}Importa ordini</Button></DialogFooter>
  </DialogContent></Dialog>;
}

function CsvMetric({label,value,warn}) { return <div className={`rounded-md p-3 text-center ${warn?"bg-amber-50 text-amber-900":"bg-slate-100 text-slate-900"}`}><div className="text-xl font-black">{value ?? 0}</div><div className="text-[10px] font-extrabold uppercase">{label}</div></div>; }

function EditOrderDialog({ order, onOpenChange, onSaved }) {
  const [form,setForm]=useState(EMPTY_ORDER_FORM); const [references,setReferences]=useState([]); const [saving,setSaving]=useState(false);
  useEffect(()=>{ if(!order)return; setForm({...EMPTY_ORDER_FORM,ship_name:order.ship_name||"",ship_company:order.ship_company||"",ship_address1:order.ship_address1||"",ship_address2:order.ship_address2||"",ship_zip:order.ship_zip||"",ship_city:order.ship_city||"",ship_province:order.ship_province||"",ship_country:order.ship_country||"Italia",ship_country_code:order.ship_country_code||"IT",customer_phone:order.customer_phone||"",customer_email:order.customer_email||"",note:order.note||"",items:(order.items||[]).map((item)=>({referenza_id:item.referenza_id||"",quantita:Number(item.quantita)||1}))}); api.get(`/referenze?cliente_id=${encodeURIComponent(order.cliente_id)}`).then(({data})=>setReferences(data||[])).catch((error)=>toast.error(error.response?.data?.detail||error.message)); },[order]);
  const field=(name,value)=>setForm((current)=>({...current,[name]:value}));
  const itemField=(index,name,value)=>setForm((current)=>({...current,items:current.items.map((item,itemIndex)=>itemIndex===index?{...item,[name]:value}:item)}));
  const addItem=()=>setForm((current)=>({...current,items:[...current.items,{referenza_id:"",quantita:1}]}));
  const removeItem=(index)=>setForm((current)=>({...current,items:current.items.filter((_,itemIndex)=>itemIndex!==index)}));
  const save=async()=>{ if(!form.ship_name.trim()||!form.ship_address1.trim()||!form.ship_zip.trim()||!form.ship_city.trim())return toast.error("Completa destinatario, indirizzo, CAP e città"); if(!form.items.length||form.items.some((item)=>!item.referenza_id||Number(item.quantita)<=0))return toast.error("Completa referenza e quantità di ogni prodotto"); setSaving(true); try{await api.put(`/shopify/orders/${order.id}`,form);toast.success("Ordine aggiornato e rimesso in verifica");onOpenChange(false);await onSaved();}catch(error){toast.error(error.response?.data?.detail||error.message);}finally{setSaving(false);}};
  return <Dialog open={Boolean(order)} onOpenChange={onOpenChange}><DialogContent className="max-h-[92vh] overflow-y-auto sm:max-w-4xl"><DialogHeader><DialogTitle>Modifica {order?.order_name}</DialogTitle><DialogDescription>Aggiorna destinatario e contenuto finché il picking non è iniziato.</DialogDescription></DialogHeader>
    <div className="space-y-6"><section><h3 className="mb-3 text-sm font-extrabold">Destinatario e consegna</h3><div className="grid gap-3 sm:grid-cols-2"><OrderField label="Nome e cognome" value={form.ship_name} onChange={(v)=>field("ship_name",v)}/><OrderField label="Azienda" value={form.ship_company} onChange={(v)=>field("ship_company",v)}/><OrderField label="Indirizzo" value={form.ship_address1} onChange={(v)=>field("ship_address1",v)}/><OrderField label="Interno / scala" value={form.ship_address2} onChange={(v)=>field("ship_address2",v)}/><OrderField label="CAP" value={form.ship_zip} onChange={(v)=>field("ship_zip",v)}/><OrderField label="Città" value={form.ship_city} onChange={(v)=>field("ship_city",v)}/><OrderField label="Provincia" value={form.ship_province} onChange={(v)=>field("ship_province",v)}/><OrderField label="Codice paese" value={form.ship_country_code} onChange={(v)=>field("ship_country_code",v.toUpperCase())}/><OrderField label="Telefono" value={form.customer_phone} onChange={(v)=>field("customer_phone",v)}/><OrderField label="Email" type="email" value={form.customer_email} onChange={(v)=>field("customer_email",v)}/></div></section>
      <section><div className="mb-3 flex items-center justify-between"><h3 className="text-sm font-extrabold">Prodotti nell’ordine</h3><Button type="button" variant="outline" size="sm" onClick={addItem}><Plus className="mr-2 h-4 w-4"/>Aggiungi prodotto</Button></div><div className="space-y-2">{form.items.map((item,index)=><div key={`${index}-${item.referenza_id}`} className="grid gap-2 rounded-md border border-slate-200 p-3 sm:grid-cols-[1fr_120px_40px] sm:items-end"><div><label className="text-xs font-bold">Referenza</label><Select value={item.referenza_id||undefined} onValueChange={(value)=>itemField(index,"referenza_id",value)}><SelectTrigger className="mt-1"><SelectValue placeholder="Seleziona prodotto"/></SelectTrigger><SelectContent>{references.map((reference)=><SelectItem key={reference.id} value={reference.id}>{reference.titolo} · {reference.sku||reference.ean||reference.fnsku}</SelectItem>)}</SelectContent></Select></div><div><label className="text-xs font-bold">Quantità</label><Input className="mt-1" type="number" min="1" step="1" value={item.quantita} onChange={(event)=>itemField(index,"quantita",Number(event.target.value))}/></div><Button type="button" variant="ghost" size="icon" className="text-rose-700" onClick={()=>removeItem(index)} aria-label="Rimuovi prodotto"><Trash2 className="h-4 w-4"/></Button></div>)}</div></section>
      <div><label className="text-xs font-bold">Note ordine</label><textarea className="mt-1 min-h-20 w-full rounded-md border border-slate-200 p-3 text-sm" value={form.note} onChange={(event)=>field("note",event.target.value)}/></div>
    </div><DialogFooter><Button variant="outline" onClick={()=>onOpenChange(false)}>Annulla</Button><Button onClick={save} disabled={saving}>{saving?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<Save className="mr-2 h-4 w-4"/>}Salva modifiche</Button></DialogFooter>
  </DialogContent></Dialog>;
}

function OrderField({label,value,onChange,type="text"}) { return <div><label className="text-xs font-bold">{label}</label><Input className="mt-1" type={type} value={value} onChange={(event)=>onChange(event.target.value)}/></div>; }
